//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Cliente
    {
        public GCP_Cliente()
        {
            this.GCP_Mascota = new HashSet<GCP_Mascota>();
            this.GHA_Hospedaje = new HashSet<GHA_Hospedaje>();
            this.GHA_Reserva = new HashSet<GHA_Reserva>();
        }
    
        public int CodigoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string DireccionCliente { get; set; }
    
        public virtual ICollection<GCP_Mascota> GCP_Mascota { get; set; }
        public virtual ICollection<GHA_Hospedaje> GHA_Hospedaje { get; set; }
        public virtual ICollection<GHA_Reserva> GHA_Reserva { get; set; }
    }
}
