//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHA_Lugar_Reserva
    {
        public long CodigoLugarReserva { get; set; }
        public long CodigoReserva { get; set; }
        public long CodigoLugar { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual GHA_Lugar GHA_Lugar { get; set; }
        public virtual GHA_Reserva GHA_Reserva { get; set; }
    }
}
