//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHA_Lugar_Estado
    {
        public long CodigoLugarEstado { get; set; }
        public long CodigoLugar { get; set; }
        public string Estado_lugar { get; set; }
        public int Periodo { get; set; }
        public System.DateTime FechaDia { get; set; }
    
        public virtual GHA_Lugar GHA_Lugar { get; set; }
    }
}
