//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHA_Lugar
    {
        public GHA_Lugar()
        {
            this.GHA_Lugar_Estado = new HashSet<GHA_Lugar_Estado>();
            this.GHA_Lugar_Hospedaje = new HashSet<GHA_Lugar_Hospedaje>();
            this.GHA_Lugar_Reserva = new HashSet<GHA_Lugar_Reserva>();
        }
    
        public long CodigoLugar { get; set; }
        public string DescripcionLugar { get; set; }
    
        public virtual ICollection<GHA_Lugar_Estado> GHA_Lugar_Estado { get; set; }
        public virtual ICollection<GHA_Lugar_Hospedaje> GHA_Lugar_Hospedaje { get; set; }
        public virtual ICollection<GHA_Lugar_Reserva> GHA_Lugar_Reserva { get; set; }
    }
}
