//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHA_Hospedaje
    {
        public GHA_Hospedaje()
        {
            this.GHA_Lugar_Hospedaje = new HashSet<GHA_Lugar_Hospedaje>();
        }
    
        public long CodigoHospedaje { get; set; }
        public Nullable<long> CodigoReserva { get; set; }
        public int CodigoCliente { get; set; }
        public int CodigoMascota { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public short EstadoHospedaje { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual GCP_Mascota GCP_Mascota { get; set; }
        public virtual GHA_Reserva GHA_Reserva { get; set; }
        public virtual ICollection<GHA_Lugar_Hospedaje> GHA_Lugar_Hospedaje { get; set; }
    }
}
