//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHA_Reserva
    {
        public GHA_Reserva()
        {
            this.GHA_Hospedaje = new HashSet<GHA_Hospedaje>();
            this.GHA_Lugar_Reserva = new HashSet<GHA_Lugar_Reserva>();
        }
    
        public long CodigoReserva { get; set; }
        public int CodigoCliente { get; set; }
        public int CodigoMascota { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public short EstadoReserva { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual GCP_Mascota GCP_Mascota { get; set; }
        public virtual ICollection<GHA_Hospedaje> GHA_Hospedaje { get; set; }
        public virtual ICollection<GHA_Lugar_Reserva> GHA_Lugar_Reserva { get; set; }
    }
}
