//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCenter.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BDPetCenterEntities : DbContext
    {
        public BDPetCenterEntities()
            : base("name=BDPetCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GCP_Cliente> GCP_Cliente { get; set; }
        public DbSet<GCP_Especie> GCP_Especie { get; set; }
        public DbSet<GCP_Mascota> GCP_Mascota { get; set; }
        public DbSet<GCP_Raza> GCP_Raza { get; set; }
        public DbSet<GHA_Hospedaje> GHA_Hospedaje { get; set; }
        public DbSet<GHA_Lugar> GHA_Lugar { get; set; }
        public DbSet<GHA_Lugar_Estado> GHA_Lugar_Estado { get; set; }
        public DbSet<GHA_Lugar_Hospedaje> GHA_Lugar_Hospedaje { get; set; }
        public DbSet<GHA_Lugar_Reserva> GHA_Lugar_Reserva { get; set; }
        public DbSet<GHA_Reserva> GHA_Reserva { get; set; }
    
        public virtual int usp_GrabarHospedaje(Nullable<long> codigoReserva, Nullable<int> codigoCliente, Nullable<int> codigoMascota, Nullable<long> codigoLugar, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var codigoReservaParameter = codigoReserva.HasValue ?
                new ObjectParameter("CodigoReserva", codigoReserva) :
                new ObjectParameter("CodigoReserva", typeof(long));
    
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(int));
    
            var codigoMascotaParameter = codigoMascota.HasValue ?
                new ObjectParameter("CodigoMascota", codigoMascota) :
                new ObjectParameter("CodigoMascota", typeof(int));
    
            var codigoLugarParameter = codigoLugar.HasValue ?
                new ObjectParameter("CodigoLugar", codigoLugar) :
                new ObjectParameter("CodigoLugar", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GrabarHospedaje", codigoReservaParameter, codigoClienteParameter, codigoMascotaParameter, codigoLugarParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual int usp_GrabarReserva(Nullable<int> codigoCliente, Nullable<int> codigoMascota, Nullable<long> codigoLugar, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var codigoClienteParameter = codigoCliente.HasValue ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(int));
    
            var codigoMascotaParameter = codigoMascota.HasValue ?
                new ObjectParameter("CodigoMascota", codigoMascota) :
                new ObjectParameter("CodigoMascota", typeof(int));
    
            var codigoLugarParameter = codigoLugar.HasValue ?
                new ObjectParameter("CodigoLugar", codigoLugar) :
                new ObjectParameter("CodigoLugar", typeof(long));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GrabarReserva", codigoClienteParameter, codigoMascotaParameter, codigoLugarParameter, fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual int usp_PlanificarHospedaje(Nullable<int> anio)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_PlanificarHospedaje", anioParameter);
        }
    }
}
